name: Release workflow

on:
  workflow_dispatch:


jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: SSH Command
      uses: D3rHase/ssh-command-action@v0.2.2
      with:
        host: ${{secrets.HOST}}
        user: ${{secrets.USER}}
        private_key: ${{secrets.PRIVATE_KEY}}
        command: echo "$(date +%F::%T) Run release" >> ~/logs/shell.log
